- name: Git config
  ansible.builtin.file:
    src: "{{ dotfiles_path }}/home/.gitconfig"
    dest: $HOME/.gitconfig 
    state: link

- name: tmux config
  ansible.builtin.file:
    src: "{{ dotfiles_path }}/home/.tmux.conf"
    dest: $HOME/.tmux.conf
    state: link

