- name: Enable che/nerd-fonts
  community.general.copr:
    host: copr.fedorainfracloud.org
    state: enabled
    name: che/nerd-fonts
  become: true

- name: Install fonts
  ansible.builtin.dnf:
    name:
      - nerd-fonts
      - jetbrains-mono-fonts-all
    state: latest
  become: true
