- name: Enable pgdev/ghostty
  community.general.copr:
    host: copr.fedorainfracloud.org
    state: enabled
    name: pgdev/ghostty
  become: true

- name: Install Gostty
  ansible.builtin.dnf:
    name: ghostty
    state: latest
  become: true

- name: Ghostty config
  ansible.builtin.file:
    src: "{{ dotfiles_path }}/home/.config/ghostty"
    dest: $HOME/.config/ghostty
    state: link
