- name: Install input remapper
  ansible.builtin.dnf:
    name: input-remapper
    state: latest
  become: true


- name: Symlink dotfiles input-remapper config
  ansible.builtin.file:
    src: "{{ dotfiles_path }}/home/.config/input-remapper-2"
    dest: $HOME/.config/input-remapper-2 
    state: link

- name: Enable and start input-remapper
  ansible.builtin.systemd_service:
    name: input-remapper
    enabled: true
    state: started
  become: true
