- name: Clone neovim
  ansible.builtin.git:
    repo: https://github.com/neovim/neovim.git
    dest: $HOME/neovim
    version: HEAD
    accept_hostkey: yes
    clone: yes
    update: yes
    force: yes

- name: Clean up artifacts from prior builds
  community.general.make:
    chdir: $HOME/neovim
    target: distclean
  tags:
    - molecule-idempotence-notest

- name: Build release target
  community.general.make:
    chdir: $HOME/neovim
    params:
      CMAKE_BUILD_TYPE: Release
      CMAKE_INSTALL_PREFIX: $HOME/.local
    target: install

- name: Remove existing neovim config
  ansible.builtin.file:
    path: $HOME/.config/nvim
    state: absent

- name: Symlink dotfiles neovim config
  ansible.builtin.file:
    src: "{{ dotfiles_path }}/home/.config/nvim"
    dest: $HOME/.config/nvim 
    state: link

