- name: Install flatpak
  ansible.builtin.dnf:
    name: flatpak
    state: latest
  become: true

- name: Add the flathub flatpak remote to the system installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
